USE MASTER
GO
CREATE DATABASE COMERCIO_DB
ALTER DATABASE SERV_TEC_DB COLLATE Latin1_General_CI_AI; 
GO
USE SERV_TEC_DB

GO

CREATE TABLE Categoria (
IDCat BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
DescripcionCat VARCHAR (50) NOT NULL UNIQUE
);
